language: php

php:
  - 7.0

before_script:
  #- composer self-update
  - composer install --no-interaction

script:
 - vendor/bin/phpunit --coverage-clover=coverage.clover --coverage-text

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
